### ISSUE TITLE
reference:once; query: no limit

### ISSUE THREAD

**Issue by AlisaGU** [mcfrith/last-genome-alignments#13]
Hi,
If I want the reference sequence to appear only once but no limit to query, can I do like that?
1. query as reference and reference as query
2. after get the many to one maf, use maf-swap to change the order of orginal reference and query and use this as the final result

**Comment by AlisaGU** [comment]
The reason I proposed this question is I noticed the many to one maf(4.4G, after remove the quality score line) is so big compared to one to one maf(21M).

**Comment by mcfrith** [comment]
Yes, swapping query and reference should do what you want. (I don't think it's necessary to use maf-swap afterwards, unless you have some reason I don't know about.)
