### ISSUE TITLE
Is it correct that there are overlapping blocks of query in one-to-one Maf file？

### ISSUE THREAD

**Issue by liu-wq** [mcfrith/last-genome-alignments#17]
Hi,
I have a question of one to one block.  
For example, use this script to align hg38 to mm10:
`
lastal -P8 -D1e9 -m100  -p my.train myDB genome2.fa |last-split  -f=MAF+> many-to-one.maf

last-split -r many-to-one.maf | last-postmask > out.maf
`
(The h38 was reference genome. )
In out.maf, h38 does not have overlapping blocks, but mm10 still has overlapping blocks aligned to different areas of h38.

like this:
chr           start           end             len strand chr          start      end       len strand
h38_chr1 207431560 207431874 314 + NC_000067.7 269948 269612 336 -
h38_chr1 207431938 207432653 715 + NC_000067.7 270514 269810 704 -

**Comment by liu-wq** [comment]
Do I need to do a few more steps here:
1.maf-swap
2.maf-sort
3.last-split
4.maf-swap
5.maf-sort
6.last-postmask

**Comment by mcfrith** [comment]
I think your script is guaranteed to have no overlapping blocks at all, in either genome. I guess your blocks actually don't overlap in mm10. The meaning of the - strand coordinates is a bit tricky, could that be it?

**Comment by liu-wq** [comment]
Just now I tried out what I was thinking. mm10 still has overlapping areas. So strand "-" might be the influencing factor.
I'm not sure how the last-split algorithm determines unique hits. Does the script not consider the direction of the chain? So how do we solve this?

**Comment by liu-wq** [comment]
Sorry for the inaccurate result of the translation software, "the direction of the chain" is corrected to "the direction of the strand".

**Comment by liu-wq** [comment]
What are the criteria for removing overlapping areas? For example, what block should I keep, the longest? The biggest Score? I could also write a script to remove it specifically.

**Comment by mcfrith** [comment]
In MAF coordinates, this is always the case:
end = start + len
Even for - strands. (For - strands, the coordinates are in the reverse-complemented sequence.)
I'm just guessing, but maybe you subtracted instead of adding?

**Comment by liu-wq** [comment]
Yes, I used subtracted. But when I downloaded h38-mm10-2.maf.gz from github. And  I using adding,  I discovered that one-to-one is only relative to one chromosome, right?  
Like same region align are unique hit for different chromosome chr1 and chr9: 

chr start end len chr start end len
hg38.chr1 210775976 210778148 2172 mm10.chr1 3038021 3039995 1974
hg38.chr9 99500046 99502590 2544 mm10.chr1 3038875 3041411 2536

**Comment by liu-wq** [comment]
Maybe there's something wrong with my process.  I not only split the hg38 chromosome but I also split the mm10 chromosome and ran parallel alignments. 

step1: 
`lastal -P8 -D1e9 -m100 -p  hg38.chr$i-mm10.chr$i.mat   hg38.chr$i mm10.chr$i.fa |last-split -f=MAF+> hg38.chr$i-mm10.chr$i.maf`
step 2: 
`cat hg38.chr*-mm10.chr*.maf >many2one.maf`
step 3:
`last-split -r many2one.maf | last-postmask > one2one.maf`

Since I also split mm10, do I need to add a split step between step2 and step3.
`last-split many2one.maf > many2one_2.maf`

**Comment by liu-wq** [comment]
I try this step but still have overlap.  : (

like this:
block 1 :
s h38_chr6    133726878 415 + 170805979
s NC_000067.7 192076210 479 - 195154279  the start convert to 3,077,590 , end convert to 3,078,069

block 2: 
s h38_chr16   20838404 565 +  90338345
s NC_000067.7  3077504 607 + 195154279 the end is 3,078,111

block2_start —— block1_start —— block1_end —— block2_end

Why?
I differ from the sample files in that I split the query files, and I last-train each of the split query files.

**Comment by mcfrith** [comment]
Your adding / subtracting looks perfect now.

The problem is splitting the reference genome (hg38 in your case). You need to give the whole un-split genome to `lastdb`. Otherwise it's impossible for the 1st alignment step to find globally many-to-one alignments.

**Comment by liu-wq** [comment]
Thank you!  I will change the script and try it.

And I want to get collinearity across 30 mammals. To determine orthologous genes and homologous non-coding regions, the block obtained should be as long as possible. How should I balance parameters between speed and accuracy?

Now I used MAM4 and  -m 100 for all mammals.

**Comment by mcfrith** [comment]
> To determine orthologous genes and homologous non-coding regions, the block obtained should be as long as possible.

I would be careful about that. Some genome alignment methods try too hard to get long blocks: https://doi.org/10.1186/s13059-015-0670-9.

The `maf-convert` `-J` option may be useful: https://gitlab.com/mcfrith/last/-/blob/main/doc/maf-convert.rst

> Now I used MAM4 and -m 100 for all mammals.

I think that's extremely slow-and-sensitive. Great if it doesn't take too much time (or memory). I would probably omit `-m 100` to reduce the compute burden.

**Comment by liu-wq** [comment]
Hi, 
Thank you for your answer, which is very helpful to me.
>The maf-convert -J option may be useful: https://gitlab.com/mcfrith/last/-/blob/main/doc/maf-convert.rst

last is a really comprehensive software! I would have written a script to handle it, but now I don't.

>I think that's extremely slow-and-sensitive. Great if it doesn't take too much time (or memory). I would probably omit -m 100 to reduce the compute burden.

I have tried the alignment without splitting the ref. It's faster than splitting. Two 112-CPU servers, 14 mammals, a total of 355 tasks were run in parallel for one night.
But species that are closely related to humans, such as mice and rats, have a block length (~620MB) that is less than that of species such as Carnivores or ungulates (>1GB).
In the last, I removed the non-chromosome parts (unplaced scaffold, mitochondria, etc.) of ref. and query. 
Is this the normal length? What parameters do I need to adjust to increase the total effective alignment length of rodents?

**Comment by mcfrith** [comment]
The mouse and rat genomes have evolved at a high rate (maybe because of short generation time), so they are more diverged from human than are some other mammals (e.g. dog: https://doi.org/10.1093/nar/gku104).

During evolution, many DNA blocks have been deleted, and there have been many transposon insertions, so 620MB might be what's left after that.
