### ISSUE TITLE
Tutorial error?

### ISSUE THREAD

**Issue by aderzelle** [mcfrith/last-genome-alignments#2]
Hello, I wonder if there is a mistake in the tutorial about human - chimp comparison

At this line

`last-train -P0 --revsym --matsym --gapsym -E0.05 -C2 hg38-NEAR panTro5.fa > hg38-panTro5.mat
`
It returns 

`last-train: error: no such option: -C`

Thank you :)

**Comment by mcfrith** [comment]
Thanks for pointing out this problem. That will indeed happen with slightly older versions of `last`. Please get the latest version, then it should work.
