### ISSUE TITLE
mismap statistic

### ISSUE THREAD

**Issue by ellieearmstrong** [mcfrith/last-genome-alignments#4]
Hi there,

I just have a quick question. I have roughly followed the tutorial for aligning ape-human for two very similar genomes and output into tab format (it worked wonderfully, btw, thank you so much!). I am wondering if there is documentation of what the columns are? I am looking to extract either scores and/or use the column that says e.g. "mismap=". Is the mismap value the rate of mismap per bp? Or should it be interpreted differently?

Sorry if these questions are quite juvenile, I am just digging into the results, but couldn't find anything that addressed this.

Thanks very much for your time!

**Comment by mcfrith** [comment]
Hello

many thanks for your interest in LAST. The tab format is (minimally) described in here:
http://last.cbrc.jp/doc/lastal.html
You can see it's basically a linearized version of MAF format. Scores are in the left-most column.

"Mismap" is defined in here:
http://last.cbrc.jp/doc/last-split.html

Have a nice day,
Martin
