### ISSUE TITLE
last-dotplot：a chr was cut into fragments

### ISSUE THREAD

**Issue by SCQUchenyang** [mcfrith/last-genome-alignments#5]
Hi，
thanks for your work of last. And I had do a alignment base on two species. When I used last-dotplot to get a figure,only one chromosome where show in the vertical. But there's some line cross the figure.So，how can I do to remove the needless lines?

**Comment by mcfrith** [comment]
Please could you provide a bit more information, e.g. what were your alignment and dotplot commands?

**Comment by lxy0107** [comment]
Hello! I have the same problem. I was aligning _S. cerevisiae_ chr1 to another yeast genome (chr1 to 8). I got vertical lines within each chromosome. Here's the code I used: `last-dotplot -x 2000 scI_1to1.maf`
I am pretty sure that the reference genome only has 8 headers (">1",">2", etc), and the maf file looks fine.
The image is attached.
![scI_to_km_1to1](https://github.com/user-attachments/assets/a02617e3-4936-4da8-9f9e-041e4e0f5a37)

Thank you in advance for looking into this!

**Comment by mcfrith** [comment]
Which version of LAST are you using?

**Comment by mcfrith** [comment]
Thanks for showing an example of the problem. In short, you can fix it by adding this `last-dotplot` option:
`--max-gap1=inf`

Here's what's going on. If a large part of a chromosome has no alignments, that part gets cut out, and the cut is shown as a vertical line. This cutting is sometimes necessary: without it, the dotplot might be extremely wide and short. But it can be confusing. The threshold for cutting was increased in LAST version 1519. Should it be increased further?

**Comment by lxy0107** [comment]
> Thanks for showing an example of the problem. In short, you can fix it by adding this `last-dotplot` option: `--max-gap1=inf`
> 
> Here's what's going on. If a large part of a chromosome has no alignments, that part gets cut out, and the cut is shown as a vertical line. This cutting is sometimes necessary: without it, the dotplot might be extremely wide and short. But it can be confusing. The threshold for cutting was increased in LAST version 1519. Should it be increased further?

Thanks! That makes sense. I think that it should be fine to set the default threshold to 1519, as long as people can customize it with `--max-gap1`. Maybe just need to clarify it in the docs.

**Comment by lxy0107** [comment]
> Thanks for showing an example of the problem. In short, you can fix it by adding this `last-dotplot` option: `--max-gap1=inf`
> 
> Here's what's going on. If a large part of a chromosome has no alignments, that part gets cut out, and the cut is shown as a vertical line. This cutting is sometimes necessary: without it, the dotplot might be extremely wide and short. But it can be confusing. The threshold for cutting was increased in LAST version 1519. Should it be increased further?

Also, is there a way to display the coordinates on the plot?

**Comment by mcfrith** [comment]
Yes, should probably clarify the docs about that, thanks.

For coordinates, how about `--labels1=2` or `--labels1=3`

**Comment by mcfrith** [comment]
Now clarified in the last-split doc!
