### ISSUE TITLE
last alignmet maf file connect to multiz

### ISSUE THREAD

**Issue by LiuGaoming2019** [mcfrith/last-genome-alignments#7]
last alignment outout maf file, why multiz cannot recongnize it, how to fix it

**Comment by xiaoyezao** [comment]
> last alignment outout maf file, why multiz cannot recongnize it, how to fix it

@LiuGaoming2019 Have you solved your question, what's your workaround?

**Comment by LipengKang** [comment]
@xiaoyezao Add `##maf version=1` to first line of your maf file. It works for me.

**Comment by mcfrith** [comment]
Thanks for sharing how to solve this!
