### ISSUE TITLE
dot-plot black lines issue

### ISSUE THREAD

**Issue by Tdanis** [mcfrith/last-genome-alignments#8]
Hi everyone, could you help me please with this dot-plot?
![example](https://user-images.githubusercontent.com/44096463/73745743-624d0700-475c-11ea-8db9-e144eae14c7a.png)

Could you suggest me please a way to eliminate all these vertical and horizontal black lines? 
My command is : last-dotplot -x 1000 -y 1000 -m 120 my_data.tab example.png

**Comment by mcfrith** [comment]
Hi,

those black lines are boundaries between different sequences. You could
reduce the number of sequences, e.g.
-m 30

Or you could play with these options:

  --border-pixels=INT   number of pixels between sequences (default=1)

  --border-color=COLOR  color for pixels between sequences (default=black)


Have a nice day,
Martin
https://sites.google.com/site/mcfrith/

**Comment by Tdanis** [comment]
Thank you very much .
