### ISSUE TITLE
How to merge maf files to generate a multi-genome alignment?

### ISSUE THREAD

**Issue by xiaoyezao** [mcfrith/last-genome-alignments#9]
Hi,

Thanks for designing this great tool to perform genome alignment.  

I did one vs one alignment for 5 species and generated 10 pair-wise genome alignments. How to merge these *.maf files to get a multi-species alignment?

Thanks,

Tao

**Comment by mcfrith** [comment]
Hi

LAST has a minimal ability to do this, with maf-join:
http://last.cbrc.jp/doc/last-scripts.txt
This is the most crude and simple possible way to join pairwise alignments into a multi-species alignment. It might be good enough...
